apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qs69cz9xs-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:2a11c851f7948e98a61cd926ebf59876c4154fc0@sha256:df1137c409188133625bf9d38cce5d1177ba1853ba4a6538a3f3b9f1859eb1ae
          name: container-image
